server:
  port: 8888

spring:
  profiles:
    active: dev
  config:
    import: optional:configtree:E:/etc/config/*/
  messages:
    basename: i18n/message
  cache:
    type: redis
  data:
    redis:
      database: 2
      host: 192.168.247.128
      port: 6379
      timeout: 5000
  mail:
    host: 
    protocol: smtps
    port: 
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            

name: classpathapplication


my:
  service:
    remote-address: 192.168.1.1
    security:
      username: "admin"
      roles:
      - "USER"
      - "ADMIN"
  session-timeout: 30m
  number: 5

---

spring:
  config:
    activate:
      on-profile: dev
      
name: multidev