server:
  port: 8877

management:
  server:
    port: 9999
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
      mode: "full"
    java:
      enabled: true
    os:
      enabled: true
  atlas:
    metrics:
      export:
        uri: "http://192.168.247.128:7101/api/v1/publish"
  tracing:
    sampling:
      probability: 1.0
      
  zipkin:
    tracing:
      endpoint: "http://192.168.247.128:9411/api/v2/spans"

info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"      

spring:
  main:
    allow-circular-references: false
  profiles:
    active: dev
  #config:
  #  import: optional:configtree:/etc/config/*/
  messages:
    basename: i18n/message
  cache:
    type: redis
  data:
    redis:
      database: 2
      host: 192.168.247.128
      port: 6379
      timeout: 5000
      password: 123456
    mongodb:
      host: 192.168.247.128
      port: 27017
      database: chat
  mail:
    host: 
    protocol: smtps
    port: 
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  rabbitmq:
    host: 192.168.247.128
    port: 5672
    username: admin
    password: admin
    
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

name: classpathapplication

app:
  datasource:
    first:
      url: "jdbc:mysql://localhost/first"
      username: "root"
      password: "123456"
      driver-class-name: com.mysql.cj.jdbc.Driver
      configuration:
        maximum-pool-size: 30

    second:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: "jdbc:mysql://localhost/second"
      username: "root"
      password: "123456"
      max-total: 30

my:
  service:
    remote-address: 192.168.1.1
    security:
      username: "admin"
      roles:
      - "USER"
      - "ADMIN"
  session-timeout: 30m
  number: 5

---

spring:
  config:
    activate:
      on-profile: dev
      
name: multidev